version: '1'

services:
  dev-rds:
    image: redis
    container_name: dev-rds-ctn
    ports:
      - "6379:6379"
  dev-mysql:
    image: bitnami/mysql:latest
    container_name: dev-mysql-ctn
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dev
      - MYSQL_CHARSET=utf8mb4